name: Calculator CI CD

permissions:
  contents: write

on:
  push:
    branches: [ main, master ]
    tags: [ "v*" ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.11']

    steps:
    # 1. Загрузка актуального состояния с сервера
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Настройка Python и сборка проекта
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Установка системных зависимостей для tkinter (только для Linux)
    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk tk-dev

    # 3. Выполнение unittest
    - name: Run unit tests
      run: |
        python -m unittest unittests.py -v

    # 4. Создание установщика
    - name: Build installer
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
        # Сборка исполняемого файла
        pyinstaller --onefile --windowed --name "calculator-${{ runner.os }}-${{ matrix.python-version }}" calculator.py

    # 5. Копирование исполняемого файла Windows в директорию с установщиков
    - name: Copy exe to Windows Installer directory
      if: runner.os == 'Windows'
      run: |
        Copy-Item "dist\calculator-Windows-${{ matrix.python-version }}.exe" "Installers\Windows\Windows Installer ${{ matrix.python-version }}\dist\" -Force

    # 6. Создание установщиков Windows
    - name: Build Installers (Windows)
      if: runner.os == 'Windows'
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: Installers\Windows\Windows Installer ${{ matrix.python-version }}\windows-installer-${{ matrix.python-version }}.iss

    # 7. Установка приложения (только для Linux)
    - name: Install application
      if: runner.os == 'Linux'
      run: |
        chmod +x dist/calculator-${{ runner.os }}-${{ matrix.python-version }}
        sudo cp dist/calculator-${{ runner.os }}-${{ matrix.python-version }} /usr/local/bin/

    # 8. Создание установщиков Linus
    - name: Build DEB installer (Linux)
      if: runner.os == 'Linux'
      run: |
        chmod +x "Installers/Debian/Debian Installer ${{ matrix.python-version }}/build_deb.sh"
        bash "Installers/Debian/Debian Installer ${{ matrix.python-version }}/build_deb.sh"

    # 9. Создание релизного артефакта
    - name: Create release artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator-${{ matrix.os }}-${{ matrix.python-version }}
        path: |
          dist/calculator-${{ runner.os }}-${{ matrix.python-version }}
          dist/calculator-${{ runner.os }}-${{ matrix.python-version }}.exe
          Installers/Windows/*/Output/*.exe
          Installers/Debian/*/*.deb

  deployment:
    runs-on: ubuntu-latest
    needs: test-and-build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: List artifacts
      run: ls -R
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          **/calculator*
          **/calculator*.*
          **/*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
